name: Publish Website to CPanel

on:
  push:
    branches:
      - master
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Initialize git repository
        run: |
          git init  # Initializes a Git repository in case it's not already a Git repo
          git add .  # Adds all files to staging
          git commit -m "Initialize repository" || echo "Already a git repo, skipping init"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.xpart.top  # Your FTP server
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Your FTP username from secrets
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password from secrets
          local-dir: './portfolio.xpart.top'  # Local directory to upload
